name: colourswift_cloud
description: Cross-platform ColourSwift Cloud File Manager.
publish_to: "none"
version: 2.0.2+1710


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  disk_space_plus: ^0.2.6
  device_info_plus: ^10.1.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.3.0
  package_info_plus: ^9.0.0
  ffi: ^2.1.4
  video_player: ^2.9.2
  image: ^4.2.0
  workmanager: ^0.6.0
  flutter_local_notifications: ^17.2.3
  crypto: ^3.0.3
  animate_do: ^3.3.4
  flutter_foreground_task: ^4.2.0
  qr_flutter: ^4.1.0

  just_audio: ^0.9.38
  video_thumbnail: ^0.5.6
  app_installer: ^1.3.1

  # --- Core UI / Logic ---
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.7
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.7+1
  photo_view: ^0.15.0

  # --- File / WebDAV ---
  dio: ^5.7.0
  webdav_client: ^1.2.1
  file_picker: ^8.1.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.2
  path: ^1.9.0
  open_filex: ^4.5.0
  share_plus: ^10.0.0
  archive: ^3.6.1
  flutter_html: ^3.0.0
  network_info_plus: ^4.0.1


  # --- Storage / Cache / Security ---
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- Optional future AI integration ---
  http: ^1.2.2
  pdfx: ^2.9.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  ffi:
    git:
      url: https://github.com/dart-lang/ffi.git
      ref: main

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/icons/logo.svg
    - assets/defs/defs.vxpack
    - assets/defs/defs_key.bin

# --- Launcher icon ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true

# --- Splash screen ---
#flutter_native_splash:
 # color: "#121212"
 # image: assets/icons/splash_logo.png
 # branding_mode: center
 # android_12:
  #  image: assets/icons/splash_logo.png
   # color: "#121212"
